api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/config/api_platform'

    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            items_per_page: 10 # Default value
            client_items_per_page: true # Disabled by default
            items_per_page_parameter_name: limit # Default value
