vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        media_product:
            uri_prefix: /media/product
            upload_destination: '%kernel.project_dir%/public/media/product'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
